CO2Cap: 2
CO2CapPeriods: 20
CO2CapWiggle: 0.0
CapacityReserveMargin: 0
EnergyShareRequirement: 0
MethodofMorris: 0
MinCapReq: 0
ModelingToGenerateAlternativeIterations: 3
ModelingToGenerateAlternatives: 0
ModelingtoGenerateAlternativeSlack: 0.1
NetworkExpansion: 0
OperationWrapping: 1
OverwriteResults: 0
ParameterScale: 0
PrintModel: 0
Reserves: 0
Solver: Gurobi
StorageLosses: 0
TimeDomainReduction: 1
TimeDomainReductionFolder: tdr_setup
Trans_Loss_Segments: 1
UCommit: 2
WriteShadowPrices: 0
